# See https://pre-commit.com for more information
# This config ensures code quality, security, cost analysis, and formatting for Tofu and general files

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v1.0.0
    hooks:
      - id: tofu_fmt
      - id: tofu_validate
        args:
          - --hook-config=--retry-once-with-cleanup=true

      - id: tofu_providers_lock
        args:
        - --hook-config=--mode=only-check-is-current-lockfile-cross-platform
      - id: tofu_tflint
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.2
    hooks:
      - id: terraform_docs
        args:
          - --hook-config=--add-to-existing-file=true # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
